name: Docker Login

on: 
  workflow_dispatch:
  push:
    branches:
      - main
    
jobs:
   first:
        runs-on: ubuntu-latest
        steps:
         - name: Docker Login
           uses: docker/login-action@v2
           with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}

       