name: Print Data

on: 
  workflow_dispatch:
  push:
    branches:
      - main
    
jobs:
   first:
        runs-on: ubuntu-latest
        steps:
        - name: Print Data
          run: echo "Hello Dear , Amal sayed amin hassan" >> README.md

        - name: Print README.md
          run: cat README.md