name: first w.f

on: 
  workflow_dispatch:
  push:
    branches:
      - main
    
jobs:
   first:
        name: 
        runs-on: ubuntu-latest
        steps:
        - name: print msg
          uses: echo "Amal"

        